import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import toast from 'react-hot-toast';
import { HiOutlineBookOpen, HiOutlineKey, HiOutlineDuplicate, HiOutlineShare, HiOutlineQrcode, HiOutlineArrowRight } from 'react-icons/hi';
import { Button } from '@/components/ui/Button';
import { GlassCard } from '@/components/ui/GlassCard';
import { EmptyState } from '@/components/ui/EmptyState';
import { QRSheet } from '@/components/ui/QRSheet';
import { useMyTeacherRecord } from '@/hooks/useMyTeacherRecord';
import { useJoinCodes } from '@/hooks/useJoinCodes';
import { useAuthStore } from '@/store/authStore';
import { createTeacher, updateTeacher } from '@/services/teachers.service';
import { CLASS_OPTIONS } from '@/schemas/student.schema';
import { useState } from 'react';
import type { ClassJoinCodeDoc } from '@/schemas/joinCode.schema';

export default function TeacherClassVerify() {
  const navigate = useNavigate();
  const user = useAuthStore((s) => s.user);
  const { data: teacher, isLoading: teacherLoading, myClasses, refetch: refetchTeacher } = useMyTeacherRecord();
  const { data: codes = [], isLoading: codesLoading } = useJoinCodes(teacher?.id);
  const [qrCodeId, setQrCodeId] = useState<string | null>(null);

  const [newClass, setNewClass] = useState<string>(CLASS_OPTIONS[3]);
  const [newSubject, setNewSubject] = useState('');
  const [newPhone, setNewPhone] = useState('');
  const [creating, setCreating] = useState(false);

  /**
   * Lets a teacher who signed up on their own create their first class.
   *
   * Previously this screen was a dead end for self-signup: `ProfileSetup` only writes
   * to the `users` doc, so no `teachers` record existed, `myClasses` was always empty,
   * and the only option was "Go to Dashboard Anyway" — landing on a dashboard with no
   * class, no students and no join code. Join codes were only ever generated from the
   * Admin teacher form, so a teacher could never obtain one, and without a code no
   * parent or student could join anything.
   *
   * This routes through the existing `createTeacher` / `updateTeacher` services, which
   * already call `ensureJoinCodesForTeacher` internally — so the code is generated by
   * the same verified path the admin flow uses, not a parallel one.
   */
  const handleCreateClass = async () => {
    if (!newSubject.trim()) {
      toast.error('Enter the subject you teach');
      return;
    }
    if (!/^[0-9+\-\s]{7,15}$/.test(newPhone.trim())) {
      toast.error('Enter a valid phone number');
      return;
    }
    if (!user?.email) {
      toast.error('No signed-in email found. Please sign in again.');
      return;
    }

    setCreating(true);
    try {
      if (teacher) {
        // Teacher record already exists (created by an admin) but has no classes yet —
        // append rather than replace, so an admin-assigned list is never clobbered.
        const merged = [...myClasses, newClass].filter(Boolean).join(', ');
        await updateTeacher(teacher.id, {
          classes: merged,
          name: teacher.name || user.name,
          email: teacher.email || user.email,
        });
      } else {
        await createTeacher({
          name: user.name || 'Teacher',
          email: user.email,
          subject: newSubject.trim(),
          classes: newClass,
          phone: newPhone.trim(),
          status: 'active',
          avatar: '',
        });
      }

      // Only the teacher record needs an explicit re-read. `useJoinCodes` is an
      // onSnapshot subscription keyed on teacher.id, so once the new id lands it
      // re-subscribes and the generated code appears on its own — no refetch needed
      // (and none available: that hook returns { data, isLoading, isError } only).
      await refetchTeacher();
      toast.success(`${newClass} created — join code generated`);
    } catch (err) {
      console.error(err);
      toast.error('Could not create the class. Please try again.');
    } finally {
      setCreating(false);
    }
  };

  const qrCode: ClassJoinCodeDoc | null = codes.find((c) => c.id === qrCodeId) ?? null;

  const copyCode = async (code: string) => {
    try {
      await navigator.clipboard.writeText(code);
      toast.success('Code copied');
    } catch {
      toast.error('Could not copy — copy it manually');
    }
  };

  const shareCode = async (className: string, code: string) => {
    const text = `Join ${className} on Smart School FinTech using this code: ${code}`;
    if (navigator.share) {
      try {
        await navigator.share({ text });
      } catch {
        // cancelled
      }
    } else {
      await copyCode(code);
    }
  };

  if (teacherLoading || codesLoading) {
    return (
      <div className="min-h-screen bg-animated flex items-center justify-center">
        <div className="w-10 h-10 rounded-full border-2 border-blush-400 border-t-transparent animate-spin" />
      </div>
    );
  }

  const hasClasses = teacher && myClasses.length > 0;

  return (
    <div className="min-h-screen bg-animated flex flex-col justify-center px-6 safe-top safe-bottom">
      <div className="max-w-md mx-auto w-full">
        {!hasClasses ? (
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6">
            <div className="w-12 h-12 rounded-2xl glass flex items-center justify-center mb-5">
              <HiOutlineBookOpen size={22} className="text-blush-600" />
            </div>
            <h1 className="font-display text-2xl font-semibold mb-1">Create Your Class</h1>
            <p className="text-sm text-blush-800/60 dark:text-blush-100/50 mb-6 leading-relaxed">
              Set up the class you teach. We'll generate a secure join code you can share
              with students and parents.
            </p>

            <div className="space-y-3 mb-6">
              <div>
                <label className="text-xs font-medium text-blush-800/70 dark:text-blush-100/60 mb-1.5 block">
                  Class
                </label>
                <select
                  value={newClass}
                  onChange={(e) => setNewClass(e.target.value)}
                  className="w-full glass-input px-4 py-3 rounded-xl2 text-sm bg-transparent"
                >
                  {CLASS_OPTIONS.map((option) => (
                    <option key={option} value={option}>{option}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="text-xs font-medium text-blush-800/70 dark:text-blush-100/60 mb-1.5 block">
                  Subject
                </label>
                <input
                  value={newSubject}
                  onChange={(e) => setNewSubject(e.target.value)}
                  placeholder="e.g. Mathematics"
                  className="w-full glass-input px-4 py-3 rounded-xl2 text-sm bg-transparent"
                />
              </div>

              <div>
                <label className="text-xs font-medium text-blush-800/70 dark:text-blush-100/60 mb-1.5 block">
                  Phone
                </label>
                <input
                  value={newPhone}
                  onChange={(e) => setNewPhone(e.target.value)}
                  placeholder="e.g. 9876543210"
                  inputMode="tel"
                  className="w-full glass-input px-4 py-3 rounded-xl2 text-sm bg-transparent"
                />
              </div>
            </div>

            <Button
              fullWidth
              size="lg"
              disabled={creating}
              onClick={handleCreateClass}
            >
              {creating ? 'Creating class…' : 'Create Class & Generate Code'}
            </Button>
          </motion.div>
        ) : (
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6">
            <div className="w-12 h-12 rounded-2xl glass flex items-center justify-center mb-5">
              <HiOutlineKey size={22} className="text-blush-600" />
            </div>
            <h1 className="font-display text-2xl font-semibold mb-1">Your Classes</h1>
            <p className="text-sm text-blush-800/60 dark:text-blush-100/50 mb-6">
              You've been assigned to the following classes. Share the join codes with your students!
            </p>

            <div className="space-y-3 mb-6 max-h-[50vh] overflow-y-auto no-scrollbar">
              {codes.map((c) => (
                <GlassCard key={c.id} padding="md" className="flex items-center gap-3">
                  <div className="min-w-0 flex-1 text-left">
                    <p className="font-semibold text-sm truncate">{c.className}</p>
                    <p className="font-display font-semibold text-lg tracking-[0.2em] mt-0.5">{c.code}</p>
                  </div>
                  <div className="flex items-center gap-1.5 shrink-0">
                    <button
                      onClick={() => setQrCodeId(c.id)}
                      className="w-8 h-8 rounded-xl flex items-center justify-center glass-pill"
                    >
                      <HiOutlineQrcode size={14} />
                    </button>
                    <button
                      onClick={() => copyCode(c.code)}
                      className="w-8 h-8 rounded-xl flex items-center justify-center glass-pill"
                    >
                      <HiOutlineDuplicate size={14} />
                    </button>
                    <button
                      onClick={() => shareCode(c.className, c.code)}
                      className="w-8 h-8 rounded-xl flex items-center justify-center glass-pill"
                    >
                      <HiOutlineShare size={14} />
                    </button>
                  </div>
                </GlassCard>
              ))}
              {codes.length === 0 && (
                 <EmptyState
                  icon={HiOutlineKey}
                  title="No join codes yet"
                  description="Codes are generated automatically. Check back soon."
                />
              )}
            </div>

            <Button
              fullWidth
              size="lg"
              icon={<HiOutlineArrowRight size={20} />}
              onClick={() => navigate('/teacher', { replace: true })}
            >
              Continue to Dashboard
            </Button>
          </motion.div>
        )}
      </div>

      <QRSheet
        open={!!qrCode}
        onClose={() => setQrCodeId(null)}
        title="Class Join Code"
        subtitle={qrCode ? qrCode.className : undefined}
        value={qrCode ? JSON.stringify({ type: 'join_code', code: qrCode.code, className: qrCode.className }) : ''}
        hint="Students and parents can scan this to join."
      />
    </div>
  );
}
